"use client";
import { useEffect, useState } from "react";

type Make={id:string;nameAr:string;nameEn:string;logoUrl:string|null;isActive:boolean;displayOrder:number};
type Model={id:string;makeId:string;nameAr:string;nameEn:string;isActive:boolean};
type Generation={id:string;modelId:string;nameAr:string|null;nameEn:string;yearFrom:number;yearTo:number|null;isActive:boolean};
type Engine={id:string;generationId:string;nameEn:string;displacement:string|null;fuelType:string|null;power:string|null;isActive:boolean};

async function api(url:string, options?:RequestInit){const r=await fetch(url,options);const d=await r.json();if(!r.ok)throw new Error(d.error||"حدث خطأ");return d;}
export default function VehiclesAdmin(){
 const [makes,setMakes]=useState<Make[]>([]),[models,setModels]=useState<Model[]>([]),[gens,setGens]=useState<Generation[]>([]),[engines,setEngines]=useState<Engine[]>([]);
 const [makeId,setMakeId]=useState(""),[modelId,setModelId]=useState(""),[genId,setGenId]=useState(""); const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [tab,setTab]=useState<"makes"|"models"|"generations"|"engines">("makes"); const [form,setForm]=useState<Record<string,string>>({});
 const load=async()=>{setLoading(true);try{const m=await api("/api/admin/vehicles/makes");setMakes(m.makes);if(!makeId&&m.makes[0])setMakeId(m.makes[0].id);}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(makeId)api(`/api/admin/vehicles/models?makeId=${makeId}`).then(d=>{setModels(d.models);if(!modelId&&d.models[0])setModelId(d.models[0].id)}).catch(e=>setError(e.message));else setModels([])},[makeId]);
 useEffect(()=>{if(modelId)api(`/api/admin/vehicles/generations?modelId=${modelId}`).then(d=>{setGens(d.generations);if(!genId&&d.generations[0])setGenId(d.generations[0].id)}).catch(e=>setError(e.message));else setGens([])},[modelId]);
 useEffect(()=>{if(genId)api(`/api/admin/vehicles/engines?generationId=${genId}`).then(d=>setEngines(d.engines)).catch(e=>setError(e.message));else setEngines([])},[genId]);
 const save=async()=>{setBusy(true);setError("");try{let url="",payload:any={...form}; if(tab==="makes")url="/api/admin/vehicles/makes"; if(tab==="models"){url="/api/admin/vehicles/models";payload.makeId=makeId} if(tab==="generations"){url="/api/admin/vehicles/generations";payload.modelId=modelId} if(tab==="engines"){url="/api/admin/vehicles/engines";payload.generationId=genId} await api(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});setForm({});await load(); if(tab==="models"&&makeId){const d=await api(`/api/admin/vehicles/models?makeId=${makeId}`);setModels(d.models)} if(tab==="generations"&&modelId){const d=await api(`/api/admin/vehicles/generations?modelId=${modelId}`);setGens(d.generations)} if(tab==="engines"&&genId){const d=await api(`/api/admin/vehicles/engines?generationId=${genId}`);setEngines(d.engines)}}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const deactivate=async(url:string,id:string)=>{if(!confirm("تعطيل هذا العنصر؟"))return;setBusy(true);try{await api(`${url}?id=${id}`,{method:"DELETE"});if(url.includes("makes"))await load();if(url.includes("models")){const d=await api(`/api/admin/vehicles/models?makeId=${makeId}`);setModels(d.models)}if(url.includes("generations")){const d=await api(`/api/admin/vehicles/generations?modelId=${modelId}`);setGens(d.generations)}if(url.includes("engines")){const d=await api(`/api/admin/vehicles/engines?generationId=${genId}`);setEngines(d.engines)}}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 if(loading)return <div className="p-6">جاري التحميل...</div>;
 return <div className="p-4 sm:p-6" dir="rtl"><div className="flex flex-col gap-2 mb-5"><h1 className="text-xl font-bold text-gray-900">السيارات</h1><p className="text-sm text-gray-500">إدارة الماركات والموديلات والأجيال والمحركات</p></div>
  {error&&<div className="mb-4 rounded-lg bg-red-50 text-red-700 p-3 text-sm">{error}</div>}
  <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-5"><div><label className="text-xs text-gray-500">الماركة</label><select className="w-full border rounded-lg p-2.5 mt-1" value={makeId} onChange={e=>{setMakeId(e.target.value);setModelId("");setGenId("")}}><option value="">اختر</option>{makes.map(x=><option key={x.id} value={x.id}>{x.nameAr} — {x.nameEn}</option>)}</select></div><div><label className="text-xs text-gray-500">الموديل</label><select className="w-full border rounded-lg p-2.5 mt-1" value={modelId} onChange={e=>{setModelId(e.target.value);setGenId("")}}><option value="">اختر</option>{models.map(x=><option key={x.id} value={x.id}>{x.nameAr} — {x.nameEn}</option>)}</select></div><div><label className="text-xs text-gray-500">الجيل</label><select className="w-full border rounded-lg p-2.5 mt-1" value={genId} onChange={e=>setGenId(e.target.value)}><option value="">اختر</option>{gens.map(x=><option key={x.id} value={x.id}>{x.nameEn} ({x.yearFrom}{x.yearTo?`-${x.yearTo}`:"+"})</option>)}</select></div></div>
  <div className="flex gap-2 overflow-x-auto border-b mb-5">{([['makes','الماركات'],['models','الموديلات'],['generations','الأجيال'],['engines','المحركات']] as const).map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`px-4 py-2.5 text-sm whitespace-nowrap ${tab===k?'border-b-2 border-[#1565C0] text-[#1565C0] font-semibold':'text-gray-500'}`}>{l}</button>)}</div>
  <div className="bg-white border rounded-xl p-4 mb-5"><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">{tab==='makes'&&<><input className="border rounded-lg p-2.5" placeholder="الاسم العربي" value={form.nameAr||""} onChange={e=>setForm({...form,nameAr:e.target.value})}/><input className="border rounded-lg p-2.5" placeholder="الاسم الإنجليزي" value={form.nameEn||""} onChange={e=>setForm({...form,nameEn:e.target.value})}/><input className="border rounded-lg p-2.5" placeholder="رابط اللوجو" value={form.logoUrl||""} onChange={e=>setForm({...form,logoUrl:e.target.value})}/><input className="border rounded-lg p-2.5" placeholder="الترتيب" type="number" value={form.displayOrder||""} onChange={e=>setForm({...form,displayOrder:e.target.value})}/></>}{tab==='models'&&<><input className="border rounded-lg p-2.5" placeholder="الاسم العربي" value={form.nameAr||""} onChange={e=>setForm({...form,nameAr:e.target.value})}/><input className="border rounded-lg p-2.5" placeholder="الاسم الإنجليزي" value={form.nameEn||""} onChange={e=>setForm({...form,nameEn:e.target.value})}/></>}{tab==='generations'&&<><input className="border rounded-lg p-2.5" placeholder="الاسم العربي" value={form.nameAr||""} onChange={e=>setForm({...form,nameAr:e.target.value})}/><input className="border rounded-lg p-2.5" placeholder="الاسم الإنجليزي" value={form.nameEn||""} onChange={e=>setForm({...form,nameEn:e.target.value})}/><input className="border rounded-lg p-2.5" placeholder="من سنة" type="number" value={form.yearFrom||""} onChange={e=>setForm({...form,yearFrom:e.target.value})}/><input className="border rounded-lg p-2.5" placeholder="إلى سنة (اختياري)" type="number" value={form.yearTo||""} onChange={e=>setForm({...form,yearTo:e.target.value})}/></>}{tab==='engines'&&<><input className="border rounded-lg p-2.5" placeholder="اسم المحرك" value={form.nameEn||""} onChange={e=>setForm({...form,nameEn:e.target.value})}/><input className="border rounded-lg p-2.5" placeholder="السعة" value={form.displacement||""} onChange={e=>setForm({...form,displacement:e.target.value})}/><input className="border rounded-lg p-2.5" placeholder="نوع الوقود" value={form.fuelType||""} onChange={e=>setForm({...form,fuelType:e.target.value})}/><input className="border rounded-lg p-2.5" placeholder="القوة" value={form.power||""} onChange={e=>setForm({...form,power:e.target.value})}/></>}</div><button disabled={busy||(tab==='models'&&!makeId)||(tab==='generations'&&!modelId)||(tab==='engines'&&!genId)} onClick={save} className="mt-3 bg-[#1565C0] text-white px-5 py-2.5 rounded-lg text-sm disabled:opacity-50">إضافة</button></div>
  <div className="bg-white border rounded-xl overflow-hidden">{tab==='makes'&&<List rows={makes} name={(x:any)=>`${x.nameAr} — ${x.nameEn}`} onDelete={x=>deactivate('/api/admin/vehicles/makes',x.id)}/>} {tab==='models'&&<List rows={models} name={(x:any)=>`${x.nameAr} — ${x.nameEn}`} onDelete={x=>deactivate('/api/admin/vehicles/models',x.id)}/>} {tab==='generations'&&<List rows={gens} name={(x:any)=>`${x.nameEn} (${x.yearFrom}${x.yearTo?`-${x.yearTo}`:"+"})`} onDelete={x=>deactivate('/api/admin/vehicles/generations',x.id)}/>} {tab==='engines'&&<List rows={engines} name={(x:any)=>`${x.nameEn}${x.displacement?` — ${x.displacement}`:""}`} onDelete={x=>deactivate('/api/admin/vehicles/engines',x.id)}/>}</div>
 </div>
}
function List({rows,name,onDelete}:{rows:any[];name:(x:any)=>string;onDelete:(x:any)=>void}){return <div>{rows.length===0?<div className="p-6 text-sm text-gray-500">لا توجد بيانات</div>:rows.map(x=><div key={x.id} className="flex items-center justify-between gap-3 p-3 border-b last:border-b-0"><span className="text-sm text-gray-800">{name(x)}</span><button onClick={()=>onDelete(x)} className="text-xs text-red-600">تعطيل</button></div>)}</div>}
