import { NextRequest, NextResponse } from "next/server";
import { db } from "@/db";
import { vehicleEngines } from "@/db/schema";
import { asc, eq } from "drizzle-orm";
import { requireAdmin } from "@/lib/auth";
export async function GET(req:NextRequest){try{await requireAdmin();const generationId=new URL(req.url).searchParams.get("generationId");const rows=await db.select().from(vehicleEngines).where(generationId?eq(vehicleEngines.generationId,generationId):undefined).orderBy(asc(vehicleEngines.nameEn));return NextResponse.json({engines:rows});}catch(e){console.error(e);return NextResponse.json({error:"تعذر تحميل المحركات"},{status:500});}}
export async function POST(req:NextRequest){try{await requireAdmin();const b=await req.json();if(!b.generationId||!b.nameEn)return NextResponse.json({error:"الجيل واسم المحرك مطلوبان"},{status:400});const [row]=await db.insert(vehicleEngines).values({generationId:b.generationId,nameEn:b.nameEn,displacement:b.displacement||null,fuelType:b.fuelType||null,power:b.power||null,isActive:b.isActive!==false}).returning();return NextResponse.json({engine:row});}catch(e){console.error(e);return NextResponse.json({error:"تعذر الحفظ"},{status:500});}}
export async function PATCH(req:NextRequest){try{await requireAdmin();const b=await req.json();if(!b.id||!b.generationId||!b.nameEn)return NextResponse.json({error:"البيانات مطلوبة"},{status:400});const [row]=await db.update(vehicleEngines).set({generationId:b.generationId,nameEn:b.nameEn,displacement:b.displacement||null,fuelType:b.fuelType||null,power:b.power||null,isActive:b.isActive!==false}).where(eq(vehicleEngines.id,b.id)).returning();return NextResponse.json({engine:row});}catch(e){console.error(e);return NextResponse.json({error:"تعذر التعديل"},{status:500});}}
export async function DELETE(req:NextRequest){try{await requireAdmin();const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"المعرف مطلوب"},{status:400});await db.update(vehicleEngines).set({isActive:false}).where(eq(vehicleEngines.id,id));return NextResponse.json({success:true});}catch(e){console.error(e);return NextResponse.json({error:"تعذر التعطيل"},{status:500});}}
