"use client";

import { useState, useEffect } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { formatPrice, ORDER_STATUS_LABELS, PAYMENT_METHOD_LABELS } from "@/lib/utils";

const STATUS_OPTIONS = [
  ["new", "جديد"], ["confirmed", "مؤكد"], ["preparing", "قيد التجهيز"], ["ready_for_shipping", "جاهز للشحن"],
  ["shipped", "تم الشحن"], ["delivered", "تم التسليم"], ["cancelled", "ملغي"], ["returned", "مرتجع"],
];
const PAYMENT_OPTIONS = [["pending", "في الانتظار"], ["paid", "مدفوع"], ["failed", "فشل"], ["refunded", "مسترد"]];
const SHIPPING_OPTIONS = [["pending", "قيد الانتظار"], ["processing", "جاري التجهيز"], ["shipped", "تم الشحن"], ["delivered", "تم التسليم"], ["returned", "مرتجع"], ["cancelled", "ملغي"]];

interface Data { order: any; items: any[]; history: any[]; payments: any[]; shipping: any; }
export default function AdminOrderDetailPage() {
  const { id } = useParams<{ id: string }>();
  const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [msg, setMsg] = useState("");
  const [status, setStatus] = useState(""); const [paymentStatus, setPaymentStatus] = useState(""); const [shippingStatus, setShippingStatus] = useState(""); const [tracking, setTracking] = useState(""); const [shippingNotes, setShippingNotes] = useState(""); const [notes, setNotes] = useState("");
  const load = async () => { setLoading(true); const r = await fetch(`/api/admin/orders/${id}`); const d = await r.json(); if (!d.error) { setData(d); setStatus(d.order.status); setPaymentStatus(d.order.paymentStatus); setShippingStatus(d.shipping?.status || "pending"); setTracking(d.shipping?.trackingNumber || ""); setShippingNotes(d.shipping?.notes || ""); } setLoading(false); };
  useEffect(() => { load(); }, [id]);
  const save = async () => { setSaving(true); setMsg(""); const r = await fetch(`/api/admin/orders/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, paymentStatus, shippingStatus, trackingNumber: tracking, shippingNotes, notes }) }); const d = await r.json(); setMsg(d.success ? "تم حفظ تحديثات الطلب" : d.error || "حدث خطأ"); if (d.success) { setNotes(""); await load(); } setSaving(false); setTimeout(() => setMsg(""), 3000); };
  if (loading) return <div className="p-6">جاري التحميل...</div>; if (!data) return <div className="p-6">الطلب غير موجود</div>;
  const o = data.order; const paymentInfo = PAYMENT_METHOD_LABELS[o.paymentMethod];
  return <div className="p-4 md:p-6 max-w-7xl mx-auto">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-5"><div><Link href="/admin/orders" className="text-sm text-gray-500">← الطلبات</Link><h1 className="text-xl md:text-2xl font-black mt-1">{o.orderNumber}</h1><p className="text-xs text-gray-500">{new Date(o.createdAt).toLocaleString("ar-EG")}</p></div><span className={`self-start px-3 py-1.5 rounded-full text-sm font-bold status-${o.status}`}>{ORDER_STATUS_LABELS[o.status]?.ar}</span></div>
    {msg && <div className="mb-4 p-3 rounded-lg bg-green-50 text-green-700 text-sm">{msg}</div>}
    <div className="grid grid-cols-1 xl:grid-cols-3 gap-5">
      <div className="xl:col-span-2 space-y-5">
        <section className="bg-white rounded-xl border p-4 md:p-5"><h2 className="font-bold mb-4">بيانات العميل والشحن</h2><div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm"><div><b>الاسم:</b> {o.customerName}</div><div><b>الهاتف:</b> <span dir="ltr">{o.customerPhone}</span></div>{o.customerEmail&&<div><b>البريد:</b> {o.customerEmail}</div>}<div className="sm:col-span-2"><b>العنوان:</b> {o.deliveryAddress}</div>{o.deliveryGovernorate&&<div><b>المحافظة:</b> {o.deliveryGovernorate}</div>}{o.deliveryCity&&<div><b>المدينة:</b> {o.deliveryCity}</div>}</div>{o.customerNotes&&<div className="mt-4 p-3 bg-yellow-50 rounded-lg text-sm"><b>ملاحظات العميل:</b> {o.customerNotes}</div>}</section>
        <section className="bg-white rounded-xl border p-4 md:p-5"><h2 className="font-bold mb-4">المنتجات ({data.items.length})</h2><div className="space-y-3">{data.items.map((x:any)=><div key={x.id} className="flex items-center gap-3 border-b pb-3 last:border-0"><div className="w-12 h-12 bg-gray-50 rounded overflow-hidden shrink-0">{x.productImageUrl&&<img src={x.productImageUrl} alt="" className="w-full h-full object-cover"/>}</div><div className="min-w-0 flex-1"><p className="font-medium text-sm truncate">{x.productNameAr}</p><p className="text-xs text-gray-400">{x.partNumber||"بدون رقم قطعة"}</p></div><div className="text-left text-sm"><b>{formatPrice(x.lineTotal)}</b><div className="text-xs text-gray-400">{formatPrice(x.unitPrice)} × {x.quantity}</div></div></div>)}</div><div className="mt-4 pt-4 border-t space-y-2 text-sm"><div className="flex justify-between"><span>المجموع</span><span>{formatPrice(o.subtotal)}</span></div>{Number(o.couponDiscount||0)>0&&<div className="flex justify-between text-green-600"><span>خصم الكوبون {o.couponCode&&`(${o.couponCode})`}</span><span>-{formatPrice(o.couponDiscount)}</span></div>}{Number(o.discountAmount||0)>Number(o.couponDiscount||0)&&<div className="flex justify-between text-green-600"><span>خصم الدفع المسبق</span><span>-{formatPrice(Number(o.discountAmount)-Number(o.couponDiscount||0))}</span></div>}<div className="flex justify-between"><span>الشحن</span><span>{formatPrice(o.shippingFee)}</span></div><div className="flex justify-between font-black text-base border-t pt-3"><span>الإجمالي</span><span className="text-[#1565C0]">{formatPrice(o.total)}</span></div></div></section>
        <section className="bg-white rounded-xl border p-4 md:p-5"><h2 className="font-bold mb-4">سجل الطلب</h2><div className="space-y-3">{data.history.map((h:any)=><div key={h.id} className="border-r-2 pr-3"><div className="text-sm font-bold">{ORDER_STATUS_LABELS[h.status]?.ar}</div>{h.notes&&<div className="text-xs text-gray-600">{h.notes}</div>}<div className="text-xs text-gray-400">{new Date(h.createdAt).toLocaleString("ar-EG")}</div></div>)}</div></section>
      </div>
      <aside className="space-y-5">
        <section className="bg-white rounded-xl border p-4 md:p-5"><h2 className="font-bold mb-4">تحديث الطلب</h2><label className="text-xs text-gray-500">حالة الطلب</label><select value={status} onChange={e=>setStatus(e.target.value)} className="w-full border rounded-lg p-2.5 mb-3 mt-1">{STATUS_OPTIONS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><label className="text-xs text-gray-500">حالة الدفع</label><select value={paymentStatus} onChange={e=>setPaymentStatus(e.target.value)} className="w-full border rounded-lg p-2.5 mb-3 mt-1">{PAYMENT_OPTIONS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><label className="text-xs text-gray-500">حالة الشحن</label><select value={shippingStatus} onChange={e=>setShippingStatus(e.target.value)} className="w-full border rounded-lg p-2.5 mb-3 mt-1">{SHIPPING_OPTIONS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><label className="text-xs text-gray-500">رقم التتبع</label><input value={tracking} onChange={e=>setTracking(e.target.value)} className="w-full border rounded-lg p-2.5 mb-3 mt-1" dir="ltr" placeholder="Tracking number"/><label className="text-xs text-gray-500">ملاحظات الشحن</label><textarea value={shippingNotes} onChange={e=>setShippingNotes(e.target.value)} className="w-full border rounded-lg p-2.5 mb-3 mt-1" rows={2}/><label className="text-xs text-gray-500">ملاحظة في سجل الطلب</label><textarea value={notes} onChange={e=>setNotes(e.target.value)} className="w-full border rounded-lg p-2.5 mb-3 mt-1" rows={2}/><button onClick={save} disabled={saving} className="w-full bg-[#1565C0] text-white rounded-lg py-3 font-bold disabled:opacity-50">{saving?"جاري الحفظ...":"حفظ التحديثات"}</button></section>
        <section className="bg-white rounded-xl border p-4 md:p-5"><h2 className="font-bold mb-3">الدفع</h2><p className="text-sm">الطريقة: <b>{paymentInfo?.ar}</b></p><p className="text-sm mt-1">الحالة: <b>{paymentStatus}</b></p></section>
        {data.shipping&&<section className="bg-white rounded-xl border p-4 md:p-5"><h2 className="font-bold mb-3">تفاصيل الشحن</h2><p className="text-sm">المزود: {data.shipping.provider||"—"}</p><p className="text-sm mt-1">الرسوم: {formatPrice(data.shipping.fee)}</p>{data.shipping.shippedAt&&<p className="text-xs text-gray-500 mt-2">شُحن: {new Date(data.shipping.shippedAt).toLocaleString("ar-EG")}</p>}{data.shipping.deliveredAt&&<p className="text-xs text-gray-500 mt-1">سُلّم: {new Date(data.shipping.deliveredAt).toLocaleString("ar-EG")}</p>}</section>}
      </aside>
    </div>
  </div>;
}
