"use client";
import { useEffect, useState } from "react";
type Customer={id:string;email:string;fullName:string|null;phone:string|null;role:string;createdAt:string;updatedAt:string;isActive:boolean};
export default function CustomersClient(){
 const [customers,setCustomers]=useState<Customer[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[q,setQ]=useState(""),[saving,setSaving]=useState<string|null>(null),[editing,setEditing]=useState<Customer|null>(null),[form,setForm]=useState({fullName:"",phone:""});
 async function load(search=q){setLoading(true);setError("");try{const r=await fetch(`/api/admin/customers${search.trim()?`?q=${encodeURIComponent(search.trim())}`:""}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error||"تعذر تحميل العملاء");setCustomers(d.customers||[])}catch(e){setError(e instanceof Error?e.message:"حدث خطأ")}finally{setLoading(false)}}
 useEffect(()=>{load("")},[]);
 async function toggle(c:Customer){setSaving(c.id);try{const r=await fetch(`/api/admin/customers/${c.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({isActive:!c.isActive})});if(!r.ok)throw Error("تعذر تحديث الحالة");await load()}catch(e){setError(e instanceof Error?e.message:"حدث خطأ")}finally{setSaving(null)}}
 async function save(){if(!editing)return;setSaving(editing.id);try{const r=await fetch(`/api/admin/customers/${editing.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw Error(d.error||"تعذر حفظ البيانات");setEditing(null);await load()}catch(e){setError(e instanceof Error?e.message:"حدث خطأ")}finally{setSaving(null)}}
 return <main dir="rtl" className="min-h-screen p-4 md:p-6"><div className="mx-auto max-w-6xl"><div className="mb-5"><h1 className="text-2xl font-bold">العملاء</h1><p className="mt-1 text-sm text-gray-500">إدارة حسابات العملاء وبيانات التواصل وحالة الحساب</p></div>
 <div className="mb-4 flex flex-col gap-2 sm:flex-row"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")load()}} placeholder="ابحث بالاسم أو البريد أو الهاتف..." className="min-w-0 flex-1 rounded-lg border bg-white px-3 py-2 text-sm"/><button onClick={()=>load()} className="rounded-lg bg-[#1565C0] px-5 py-2 text-sm font-medium text-white">بحث</button><button onClick={()=>{setQ("");load("")}} className="rounded-lg border bg-white px-4 py-2 text-sm">إظهار الكل</button></div>
 {error&&<div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 <div className="overflow-x-auto rounded-xl border bg-white">{loading?<div className="p-6 text-sm">جاري التحميل...</div>:<table className="w-full min-w-[760px] text-right text-sm"><thead className="border-b bg-gray-50"><tr>{["العميل","البريد","الهاتف","التسجيل","الحالة","إجراءات"].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{customers.map(c=><tr key={c.id} className="border-b last:border-0"><td className="p-3 font-medium">{c.fullName||"بدون اسم"}</td><td className="p-3">{c.email}</td><td className="p-3">{c.phone||"—"}</td><td className="p-3">{new Date(c.createdAt).toLocaleDateString("ar-EG")}</td><td className="p-3">{c.isActive?"نشط":"موقوف"}</td><td className="p-3"><div className="flex gap-2"><button onClick={()=>{setEditing(c);setForm({fullName:c.fullName||"",phone:c.phone||""})}} className="rounded-lg border px-3 py-1.5">تعديل</button><button disabled={saving===c.id} onClick={()=>toggle(c)} className="rounded-lg border px-3 py-1.5 disabled:opacity-50">{saving===c.id?"...":c.isActive?"إيقاف":"تفعيل"}</button></div></td></tr>)}{!customers.length&&<tr><td colSpan={6} className="p-8 text-center text-gray-500">لا يوجد عملاء مطابقون</td></tr>}</tbody></table>}</div>
 {editing&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setEditing(null)}}><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-xl"><h2 className="text-lg font-bold">تعديل بيانات العميل</h2><p className="mt-1 text-sm text-gray-500">{editing.email}</p><div className="mt-5 space-y-3"><label className="block text-sm">الاسم<input value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2"/></label><label className="block text-sm">الهاتف<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2"/></label></div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setEditing(null)} className="rounded-lg border px-4 py-2 text-sm">إلغاء</button><button onClick={save} disabled={saving===editing.id} className="rounded-lg bg-[#1565C0] px-4 py-2 text-sm text-white">{saving===editing.id?"جاري الحفظ...":"حفظ"}</button></div></div></div>}</div></main>
}
