"use client";
import { useEffect, useState } from "react";

type Coupon={id:string;code:string;descriptionAr:string|null;discountType:string;discountValue:string;minOrderAmount:string|null;maxUses:number|null;usedCount:number;expiresAt:string|null;isActive:boolean};
const empty={code:"",descriptionAr:"",discountType:"percent",discountValue:"",minOrderAmount:"0",maxUses:"",expiresAt:"",isActive:true};
export default function CouponsPage(){
 const [rows,setRows]=useState<Coupon[]>([]),[form,setForm]=useState(empty),[editing,setEditing]=useState<string|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState("");
 const load=async()=>{setLoading(true);const r=await fetch("/api/admin/coupons",{cache:"no-store"});const d=await r.json();setRows(d.coupons||[]);setLoading(false);if(!r.ok)setMsg(d.error||"خطأ");};
 useEffect(()=>{load()},[]);
 const save=async()=>{if(!form.code||!form.discountValue)return setMsg("أدخل الكود وقيمة الخصم");setSaving(true);setMsg("");const r=await fetch(editing?`/api/admin/coupons/${editing}`:"/api/admin/coupons",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,maxUses:form.maxUses||null,expiresAt:form.expiresAt||null})});const d=await r.json();setSaving(false);if(!r.ok)return setMsg(d.error||"خطأ");setMsg(editing?"تم تحديث الكوبون":"تم إنشاء الكوبون");setForm(empty);setEditing(null);load();};
 const edit=(c:Coupon)=>setEditing(c.id)||setForm({code:c.code,descriptionAr:c.descriptionAr||"",discountType:c.discountType,discountValue:c.discountValue,minOrderAmount:c.minOrderAmount||"0",maxUses:c.maxUses?.toString()||"",expiresAt:c.expiresAt?new Date(c.expiresAt).toISOString().slice(0,16):"",isActive:c.isActive});
 const toggle=async(c:Coupon)=>{await fetch(`/api/admin/coupons/${c.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({isActive:!c.isActive})});load()};
 return <main dir="rtl" className="min-h-screen p-4 md:p-6"><div className="mx-auto max-w-6xl"><div className="mb-6"><h1 className="text-2xl font-black">الكوبونات</h1><p className="mt-1 text-sm text-gray-500">إنشاء وإدارة أكواد الخصم المستخدمة في الطلبات</p></div>
 <section className="mb-6 rounded-xl border bg-white p-4"><h2 className="mb-4 font-bold">{editing?"تعديل كوبون":"إضافة كوبون"}</h2><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
 {([['code','الكود'],['descriptionAr','الوصف'],['discountValue','قيمة الخصم'],['minOrderAmount','الحد الأدنى'],['maxUses','أقصى استخدامات']] as const).map(([k,l])=><label key={k} className="text-xs font-semibold text-gray-600">{l}<input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" /></label>)}
 <label className="text-xs font-semibold text-gray-600">نوع الخصم<select value={form.discountType} onChange={e=>setForm({...form,discountType:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"><option value="percent">نسبة مئوية %</option><option value="fixed">مبلغ ثابت</option></select></label>
 <label className="text-xs font-semibold text-gray-600">تاريخ الانتهاء<input type="datetime-local" value={form.expiresAt} onChange={e=>setForm({...form,expiresAt:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" /></label>
 </div><div className="mt-4 flex gap-2"><button disabled={saving} onClick={save} className="rounded-lg bg-[#1565C0] px-5 py-2 text-sm font-bold text-white">{saving?"جاري الحفظ...":editing?"حفظ التعديل":"إضافة"}</button>{editing&&<button onClick={()=>{setEditing(null);setForm(empty)}} className="rounded-lg border px-5 py-2 text-sm">إلغاء</button>}</div>{msg&&<p className="mt-3 text-sm text-red-600">{msg}</p>}</section>
 <section className="overflow-x-auto rounded-xl border bg-white">{loading?<div className="p-6">جاري التحميل...</div>:<table className="w-full min-w-[850px] text-right text-sm"><thead className="border-b bg-gray-50"><tr>{['الكود','الخصم','الحد الأدنى','الاستخدام','الانتهاء','الحالة','إجراء'].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(c=><tr key={c.id} className="border-b last:border-0"><td className="p-3 font-bold">{c.code}</td><td className="p-3">{c.discountType==='percent'?`${c.discountValue}%`:`${c.discountValue} جنيه`}</td><td className="p-3">{c.minOrderAmount||'0'}</td><td className="p-3">{c.usedCount}{c.maxUses?` / ${c.maxUses}`:' / غير محدود'}</td><td className="p-3">{c.expiresAt?new Date(c.expiresAt).toLocaleString('ar-EG'):'بدون'}</td><td className="p-3">{c.isActive?'نشط':'متوقف'}</td><td className="p-3 flex gap-2"><button onClick={()=>edit(c)} className="rounded border px-3 py-1">تعديل</button><button onClick={()=>toggle(c)} className="rounded border px-3 py-1">{c.isActive?'إيقاف':'تفعيل'}</button></td></tr>)}{!rows.length&&<tr><td colSpan={7} className="p-8 text-center text-gray-500">لا توجد كوبونات</td></tr>}</tbody></table>}</section></div></main>;
}
