import { NextRequest, NextResponse } from "next/server";
import { db } from "@/db";
import { vehicleGenerations } from "@/db/schema";
import { asc, eq } from "drizzle-orm";
import { requireAdmin } from "@/lib/auth";
export async function GET(req:NextRequest){try{await requireAdmin();const modelId=new URL(req.url).searchParams.get("modelId");const rows=await db.select().from(vehicleGenerations).where(modelId?eq(vehicleGenerations.modelId,modelId):undefined).orderBy(asc(vehicleGenerations.yearFrom));return NextResponse.json({generations:rows});}catch(e){console.error(e);return NextResponse.json({error:"تعذر تحميل الأجيال"},{status:500});}}
export async function POST(req:NextRequest){try{await requireAdmin();const b=await req.json();if(!b.modelId||!b.nameEn||b.yearFrom===undefined)return NextResponse.json({error:"الموديل والاسم وسنة البداية مطلوبة"},{status:400});const [row]=await db.insert(vehicleGenerations).values({modelId:b.modelId,nameAr:b.nameAr||null,nameEn:b.nameEn,yearFrom:Number(b.yearFrom),yearTo:b.yearTo===""||b.yearTo==null?null:Number(b.yearTo),isActive:b.isActive!==false}).returning();return NextResponse.json({generation:row});}catch(e){console.error(e);return NextResponse.json({error:"تعذر الحفظ"},{status:500});}}
export async function PATCH(req:NextRequest){try{await requireAdmin();const b=await req.json();if(!b.id||!b.modelId||!b.nameEn||b.yearFrom===undefined)return NextResponse.json({error:"البيانات مطلوبة"},{status:400});const [row]=await db.update(vehicleGenerations).set({modelId:b.modelId,nameAr:b.nameAr||null,nameEn:b.nameEn,yearFrom:Number(b.yearFrom),yearTo:b.yearTo===""||b.yearTo==null?null:Number(b.yearTo),isActive:b.isActive!==false}).where(eq(vehicleGenerations.id,b.id)).returning();return NextResponse.json({generation:row});}catch(e){console.error(e);return NextResponse.json({error:"تعذر التعديل"},{status:500});}}
export async function DELETE(req:NextRequest){try{await requireAdmin();const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"المعرف مطلوب"},{status:400});await db.update(vehicleGenerations).set({isActive:false}).where(eq(vehicleGenerations.id,id));return NextResponse.json({success:true});}catch(e){console.error(e);return NextResponse.json({error:"تعذر التعطيل"},{status:500});}}
