"use client";
import { useRef, useState } from "react";

export interface AdminProductImage { id: string; imageUrl: string; isPrimary: boolean; displayOrder: number; }
export default function AdminProductImageManager({ productId, images, onChange }: { productId: string; images: AdminProductImage[]; onChange: (v: AdminProductImage[]) => void }) {
  const ref = useRef<HTMLInputElement>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const sorted=[...images].sort((a,b)=>a.displayOrder-b.displayOrder);
  const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];e.target.value="";if(!f)return;setError("");if(!["image/jpeg","image/png","image/webp"].includes(f.type)){setError("اختار JPEG أو PNG أو WebP");return}if(f.size>10*1024*1024){setError("حجم الصورة أكبر من 10 ميجابايت");return}setBusy(true);try{const fd=new FormData();fd.append("image",f);const r=await fetch(`/api/admin/products/${productId}/images`,{method:"POST",body:fd});const d=await r.json();if(!r.ok){setError(d.error||"فشل الرفع");return}onChange([...images,d.image])}catch{setError("خطأ في الاتصال")}finally{setBusy(false)}};
  const mutate=async(path:string,method:string,body?:unknown)=>{setError("");setBusy(true);try{const r=await fetch(path,{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok){setError(d.error||"تعذر تنفيذ العملية");return d}return d}catch{setError("خطأ في الاتصال")}finally{setBusy(false)}};
  const primary=async(id:string)=>{const d=await mutate(`/api/admin/products/${productId}/images/${id}`,"PATCH",{isPrimary:true});if(d?.success)onChange(images.map(x=>({...x,isPrimary:x.id===id})))};
  const del=async(id:string)=>{if(!confirm("حذف الصورة؟"))return;const d=await mutate(`/api/admin/products/${productId}/images/${id}`,"DELETE");if(d?.success){const left=images.filter(x=>x.id!==id);if(left.length&&!left.some(x=>x.isPrimary)){left[0]={...left[0],isPrimary:true}}onChange(left)}};
  const move=async(id:string,dir:number)=>{const i=sorted.findIndex(x=>x.id===id),j=i+dir;if(i<0||j<0||j>=sorted.length)return;[sorted[i],sorted[j]]=[sorted[j],sorted[i]];const ids=sorted.map(x=>x.id);const d=await mutate(`/api/admin/products/${productId}/images`,"PATCH",{order:ids});if(d?.success)onChange(images.map(x=>({...x,displayOrder:ids.indexOf(x.id)})))};
  return <div>{error&&<div className="mb-3 rounded-lg bg-red-50 border border-red-200 text-red-700 p-2 text-xs">{error}</div>}<div className="grid grid-cols-3 sm:grid-cols-5 gap-3">{sorted.map((img,i)=><div key={img.id} className="relative aspect-square rounded-lg overflow-hidden border bg-gray-50"><img src={img.imageUrl} alt="" className="w-full h-full object-cover"/><div className="absolute top-1 right-1">{img.isPrimary&&<span className="bg-[#1565C0] text-white text-[10px] px-1.5 py-0.5 rounded">رئيسية</span>}</div><div className="absolute bottom-0 inset-x-0 bg-black/65 p-1 flex gap-1"><button disabled={busy||i===0} onClick={()=>move(img.id,-1)} className="flex-1 bg-white rounded text-xs">↑</button><button disabled={busy||i===sorted.length-1} onClick={()=>move(img.id,1)} className="flex-1 bg-white rounded text-xs">↓</button>{!img.isPrimary&&<button disabled={busy} onClick={()=>primary(img.id)} className="flex-1 bg-white rounded text-xs">رئيسية</button>}<button disabled={busy} onClick={()=>del(img.id)} className="flex-1 bg-red-500 text-white rounded text-xs">حذف</button></div></div>)}<button type="button" disabled={busy} onClick={()=>ref.current?.click()} className="aspect-square rounded-lg border-2 border-dashed border-gray-300 flex flex-col items-center justify-center text-gray-500 text-xs gap-2 hover:border-[#1565C0] hover:text-[#1565C0]">+<span>إضافة صورة</span></button></div><input ref={ref} type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} className="hidden"/></div>;
}
