"use client";
import { useEffect, useState } from "react";

type Review = { id:string; rating:number; comment:string|null; isApproved:boolean; createdAt:string; productNameAr:string; customerName:string|null; customerEmail:string };
export default function AdminReviewsPage() {
  const [reviews,setReviews]=useState<Review[]>([]); const [status,setStatus]=useState("pending"); const [q,setQ]=useState(""); const [loading,setLoading]=useState(true); const [msg,setMsg]=useState("");
  const load=async()=>{setLoading(true); const r=await fetch(`/api/admin/reviews?status=${status}&q=${encodeURIComponent(q)}`); const d=await r.json(); setReviews(d.reviews||[]); setLoading(false);};
  useEffect(()=>{load();},[status]);
  const toggle=async(id:string,approved:boolean)=>{const r=await fetch(`/api/admin/reviews/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({isApproved:approved})}); const d=await r.json(); if(d.review){setMsg(approved?"تم اعتماد التقييم":"تم إخفاء التقييم");load();} else setMsg(d.error||"حدث خطأ"); setTimeout(()=>setMsg(""),2500);};
  return <div className="p-4 sm:p-6 max-w-6xl mx-auto" dir="rtl"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-5"><div><h1 className="text-2xl font-black text-gray-900">إدارة المراجعات</h1><p className="text-sm text-gray-500 mt-1">مراجعة تقييمات العملاء قبل ظهورها على المنتجات</p></div><div className="flex gap-2"><button onClick={()=>setStatus("pending")} className={`px-3 py-2 rounded-lg text-sm ${status==="pending"?"bg-[#1565C0] text-white":"bg-gray-100"}`}>قيد المراجعة</button><button onClick={()=>setStatus("approved")} className={`px-3 py-2 rounded-lg text-sm ${status==="approved"?"bg-[#1565C0] text-white":"bg-gray-100"}`}>المعتمدة</button></div></div>{msg&&<div className="mb-4 bg-green-50 text-green-700 rounded-lg px-4 py-3 text-sm">{msg}</div>}<div className="bg-white border border-gray-100 rounded-xl p-3 mb-4 flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="بحث بالمنتج أو العميل أو التعليق" className="flex-1 border rounded-lg px-3 py-2 text-sm outline-none"/><button onClick={load} className="bg-[#1565C0] text-white px-4 rounded-lg text-sm">بحث</button></div>{loading?<div className="text-center py-12 text-gray-500">جاري التحميل...</div>:reviews.length===0?<div className="bg-white rounded-xl border p-10 text-center text-gray-500">لا توجد مراجعات في هذه القائمة</div>:<div className="space-y-3">{reviews.map(r=><div key={r.id} className="bg-white border border-gray-100 rounded-xl p-4"><div className="flex flex-col md:flex-row md:items-start md:justify-between gap-3"><div className="min-w-0"><div className="font-bold text-gray-900">{r.productNameAr}</div><div className="text-xs text-gray-500 mt-1">{r.customerName||"عميل"} — {r.customerEmail}</div><div className="text-amber-500 text-lg mt-2">{"★".repeat(r.rating)}<span className="text-gray-200">{"★".repeat(5-r.rating)}</span></div>{r.comment&&<p className="text-sm text-gray-700 mt-2 whitespace-pre-wrap">{r.comment}</p>}<div className="text-xs text-gray-400 mt-2">{new Date(r.createdAt).toLocaleString("ar-EG")}</div></div><button onClick={()=>toggle(r.id,!r.isApproved)} className={`shrink-0 px-4 py-2 rounded-lg text-sm font-medium ${r.isApproved?"bg-red-50 text-red-600":"bg-green-50 text-green-700"}`}>{r.isApproved?"إخفاء":"اعتماد"}</button></div></div>)}</div>}</div>;
}
